version: "3.7"

services:
  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./:/usr/share/nginx/html
    networks:
      - traefik
    expose:
      - 80
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.example-tyilo-com.rule=Host(`example.tyilo.com`)
        - traefik.http.routers.example-tyilo-com.tls.certResolver=le
        - traefik.http.services.example-tyilo-com.loadbalancer.server.port=80
    container_name: example.tyilo.com

networks:
  traefik:
    external: true
