version: "3.7"

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./:/usr/share/nginx/html
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.example-tyilo-com.rule=Host(`example.test`)
      - traefik.http.services.example-tyilo-com.loadbalancer.server.port=80

networks:
  traefik:
    external: true
