version: "3.7"

networks:
  traefik:
    name: traefik

services:
  traefik:
    image: traefik:2.4
    networks:
      - traefik
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./traefik-dynamic.yml:/etc/traefik/traefik-dynamic.yml
      - ./acme.json:/acme.json
      - ./usersfile:/traefik-api-usersfile
    labels:
      - traefik.enable=true

      # Dashboard / API
      - traefik.http.routers.api.rule=Host(`traefik.tyilo.com`)
      - traefik.http.routers.api.service=api@internal
      - traefik.http.routers.api.middlewares=auth
      - traefik.http.services.api.loadbalancer.server.port=80
      - traefik.http.middlewares.auth.basicauth.usersfile=/traefik-api-usersfile
