version: "3.7"

networks:
  traefik:
    name: traefik

services:
  traefik:
    container_name: traefik
    image: traefik:2.1
    restart: always
    networks:
      - traefik
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./acme.json:/acme.json
      - ./usersfile:/traefik-api-usersfile
    labels:
      - traefik.enable=true

      # Dashboard / API
      - traefik.http.routers.api.rule=Host(`traefik.tyilo.com`)
      - traefik.http.routers.api.tls.certResolver=le
      - traefik.http.routers.api.service=api@internal
      - traefik.http.routers.api.middlewares=auth
      - traefik.http.services.api.loadbalancer.server.port=80
      - traefik.http.middlewares.auth.basicauth.usersfile=/traefik-api-usersfile

      # Redirect all http to https
      - traefik.http.routers.http-to-https.priority=1000
      - traefik.http.routers.http-to-https.rule=PathPrefix(`/`)
      - traefik.http.routers.http-to-https.entrypoints=http
      - traefik.http.routers.http-to-https.middlewares=redirect-to-https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
