#!/bin/bash
set -euo pipefail

stop_apps() {
	sudo docker-compose -f example-passthrough/docker-compose.yml down
	sudo docker-compose -f example-server/docker-compose.yml down
	sudo docker-compose down
}

test_contains() {
	cmd="curl $1"
	echo "$cmd:"
	res=$($cmd 2>&1)
	shift
	ok=true
	for s in "$@"; do
		if ! echo "$res" | grep "$s" &> /dev/null; then
			echo "  Doesn't contain: $s" >&2
			ok=false
		fi
	done

	if $ok; then
		echo "  Ok"
	else
		echo "$res" >&2
	fi
}

trap stop_apps EXIT

stop_apps

sudo docker-compose up -d

sudo docker-compose -f example-server/docker-compose.yml up -d
sudo docker-compose -f example-passthrough/docker-compose.yml up -d

sleep 5

test_contains "-i http://example.localhost/" "Location: https://example.localhost/"
test_contains "-k https://example.localhost/" "Yay"

test_contains "-i http://passthrough.localhost/" "Hi from HTTP passthrough"
test_contains "-vk https://passthrough.localhost/" "subject: CN=passthrough.localhost" "Hi from TLS passthrough"
