[log]
  level = "INFO"

[providers.docker]
  exposedByDefault = false
  network = "traefik"
  swarmMode = true

[api]
  dashboard = true

[entryPoints]
  [entryPoints.http]
    address = ":80"

    [entryPoints.http.http.redirections.entryPoint]
      to = "https"
      priority = 1000

  [entryPoints.https]
    address = ":443"

    [entryPoints.https.http.tls]
      certResolver = "le"

[certificatesResolvers.le.acme]
  email = "asgerdrewsen@gmail.com"
  storage = "acme.json"
  [certificatesResolvers.le.acme.tlsChallenge]
