log:
  level: INFO

providers:
  docker:
    exposedByDefault: false
    network: traefik

api:
  dashboard: true

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          priority: 1000

  https:
    address: ":443"
    http:
      tls:
        certResolver: le

tls:
  options:
    default:
      sniStrict: true
      minVersion: VersionTLS13

certificatesResolvers:
  le:
    acme:
      email: asgerdrewsen@gmail.com
      storage: acme.json
      tlsChallenge: {}

pilot:
  token: "c5439263-14ca-444f-8550-6bed58137e06"
