log:
  level: INFO

providers:
  docker:
    exposedByDefault: false
    network: traefik
    swarmMode: true

api:
  dashboard: true

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          priority: 1000

  https:
    address: ":443"
    http:
      tls:
        certResolver: le

certificatesResolvers:
  le:
    acme:
      email: asgerdrewsen@gmail.com
      storage: acme.json
      tlsChallenge: {}
